@startuml
hide circle
skinparam classAttributeIconSize 0

Class "<<interface>>\nParser" as Parser
Class CultureCommandParser {
  +parse(): CultureCommand
}
Class ParserException

CultureCommandParser .up.|> Parser
Parser .right.> ParserException: throws >
CultureCommandParser .right.> ParserException: throws >
@enduml
